/**
 * @description if you modify this properties, you should upgrade the minor version because it will be a break changes
 */
export const translatedVariableDictionary = {
  국회의원코드: 'lawmakerCode',
  국회의원명: 'lawmakerName',
  국회의원한자명: 'lawmakerChineseName',
  국회의원영문명: 'lawmakerEnglishName',
  생일구분코드: 'birthdayDivisionCode',
  생일일자: 'birthday',
  직책명: 'dutyName',
  정당명: 'politicalPartyName',
  선거구명: 'electoralDistrictName',
  선거구구분명: 'electoralDistrictDivisionName',
  위원회명: 'committeeName',
  소속위원회명: 'belongingCommitteeName',
  재선구분명: 're-electionClassificationDivision',
  당선대수: 'GTELT_ERACO',
  성별: 'gender',
  전화번호: 'phoneNumber',
  국회의원이메일주소: 'email',
  국회의원홈페이지URL: 'homepage',
  보좌관: 'aide',
  비서관: 'seniorSecretary',
  비서: 'secretary',
  약력: 'profile',
  사무실호실: 'officeRoom',
  사진: 'picture',

  // 의안 관련 추가
  의안ID: 'billID',
  의안번호: 'billNumber',
  대: 'age',
  의안명: 'billName',
  제안자: 'proposer',
  제안자구분: 'proposerDivision',
  제안일: 'proposeDate',
  소관위코드: 'committeeId',
  소관위: 'committee',
  소관위회부일: 'committeeDate',
  위원회심사_처리일: 'committeeReviewProcessDate',
  의안상세정보_URL: 'billDetailUrl',
  대표발의자: 'leadProposer',
  법사위처리결과: 'lawProcessResult',
  법사위처리일: 'lawProcessdate',
  법사위상정일: 'lawPresent',
  법사위회부일: 'lawSubmitDate',
  소관위처리결과: 'committeeProcessResult',
  소관위처리일: 'committeeProcessDate',
  소관위상정일: 'committeePresentDate',
  대표발의자코드: 'leadProposerCode',
  본회의심의결과: 'plenarysessionReviewResult',
  의결일: 'ResolutionDate',
} as const;
